INSERT INTO gen.Country (CountryId, Alpha1, Alpha2, Name, AreaCode, Flag, Nationality)
SELECT 
    ROW_NUMBER() OVER (ORDER BY Name) AS CountryId,
    Alpha1,
    Alpha2,
    Name,
    AreaCode,
    Flag,
    Nationality
FROM (
    VALUES
    ('AFG','AF','Afghanistan','+93',NULL,'Afghan'),
    ('ALA','AX','Åland Islands','+358',NULL,'Åland Islander'),
    ('ALB','AL','Albania','+355',NULL,'Albanian'),
    ('DZA','DZ','Algeria','+213',NULL,'Algerian'),
    ('ASM','AS','American Samoa','+1-684',NULL,'American Samoan'),
    ('AND','AD','Andorra','+376',NULL,'Andorran'),
    ('AGO','AO','Angola','+244',NULL,'Angolan'),
    ('AIA','AI','Anguilla','+1-264',NULL,'Anguillian'),
    ('ATA','AQ','Antarctica',NULL,NULL,'Antarctic'),
    ('ATG','AG','Antigua and Barbuda','+1-268',NULL,'Antiguan or Barbudan'),
    ('ARG','AR','Argentina','+54',NULL,'Argentine'),
    ('ARM','AM','Armenia','+374',NULL,'Armenian'),
    ('ABW','AW','Aruba','+297',NULL,'Aruban'),
    ('AUS','AU','Australia','+61',NULL,'Australian'),
    ('AUT','AT','Austria','+43',NULL,'Austrian'),
    ('AZE','AZ','Azerbaijan','+994',NULL,'Azerbaijani'),
    ('BHS','BS','Bahamas','+1-242',NULL,'Bahamian'),
    ('BHR','BH','Bahrain','+973',NULL,'Bahraini'),
    ('BGD','BD','Bangladesh','+880',NULL,'Bangladeshi'),
    ('BRB','BB','Barbados','+1-246',NULL,'Barbadian'),
    ('BLR','BY','Belarus','+375',NULL,'Belarusian'),
    ('BEL','BE','Belgium','+32',NULL,'Belgian'),
    ('BLZ','BZ','Belize','+501',NULL,'Belizean'),
    ('BEN','BJ','Benin','+229',NULL,'Beninese'),
    ('BMU','BM','Bermuda','+1-441',NULL,'Bermudian'),
    ('BTN','BT','Bhutan','+975',NULL,'Bhutanese'),
    ('BOL','BO','Bolivia (Plurinational State of)','+591',NULL,'Bolivian'),
    ('BES','BQ','Bonaire, Sint Eustatius and Saba','+599',NULL,'Dutch Caribbean'),
    ('BIH','BA','Bosnia and Herzegovina','+387',NULL,'Bosnian or Herzegovinian'),
    ('BWA','BW','Botswana','+267',NULL,'Botswanan'),
    ('BVT','BV','Bouvet Island',NULL,NULL,'Bouvet Islander'),
    ('BRA','BR','Brazil','+55',NULL,'Brazilian'),
    ('IOT','IO','British Indian Ocean Territory','+246',NULL,'BIOT citizen'),
    ('BRN','BN','Brunei Darussalam','+673',NULL,'Bruneian'),
    ('BGR','BG','Bulgaria','+359',NULL,'Bulgarian'),
    ('BFA','BF','Burkina Faso','+226',NULL,'Burkinabé'),
    ('BDI','BI','Burundi','+257',NULL,'Burundian'),
    ('CPV','CV','Cabo Verde','+238',NULL,'Cape Verdean'),
    ('KHM','KH','Cambodia','+855',NULL,'Cambodian'),
    ('CMR','CM','Cameroon','+237',NULL,'Cameroonian'),
    ('CAN','CA','Canada','+1',NULL,'Canadian'),
    ('CYM','KY','Cayman Islands','+1-345',NULL,'Caymanian'),
    ('CAF','CF','Central African Republic','+236',NULL,'Central African'),
    ('TCD','TD','Chad','+235',NULL,'Chadian'),
    ('CHL','CL','Chile','+56',NULL,'Chilean'),
    ('CHN','CN','China','+86',NULL,'Chinese'),
    ('CXR','CX','Christmas Island','+61',NULL,'Christmas Islander'),
    ('CCK','CC','Cocos (Keeling) Islands','+61',NULL,'Cocos Islander'),
    ('COL','CO','Colombia','+57',NULL,'Colombian'),
    ('COM','KM','Comoros','+269',NULL,'Comorian'),
    ('COG','CG','Congo','+242',NULL,'Congolese'),
    ('COD','CD','Congo, Democratic Republic of the','+243',NULL,'Congolese'),
    ('COK','CK','Cook Islands','+682',NULL,'Cook Islander'),
    ('CRI','CR','Costa Rica','+506',NULL,'Costa Rican'),
    ('CIV','CI','Côte d''Ivoire','+225',NULL,'Ivorian'),
    ('HRV','HR','Croatia','+385',NULL,'Croatian'),
    ('CUB','CU','Cuba','+53',NULL,'Cuban'),
    ('CUW','CW','Curaçao','+599',NULL,'Curaçaoan'),
    ('CYP','CY','Cyprus','+357',NULL,'Cypriot'),
    ('CZE','CZ','Czechia','+420',NULL,'Czech'),
    ('DNK','DK','Denmark','+45',NULL,'Danish'),
    ('DJI','DJ','Djibouti','+253',NULL,'Djiboutian'),
    ('DMA','DM','Dominica','+1-767',NULL,'Dominican (Dominica)'),
    ('DOM','DO','Dominican Republic','+1-809',NULL,'Dominican'),
    ('ECU','EC','Ecuador','+593',NULL,'Ecuadorian'),
    ('EGY','EG','Egypt','+20',NULL,'Egyptian'),
    ('SLV','SV','El Salvador','+503',NULL,'Salvadoran'),
    ('GNQ','GQ','Equatorial Guinea','+240',NULL,'Equatoguinean'),
    ('ERI','ER','Eritrea','+291',NULL,'Eritrean'),
    ('EST','EE','Estonia','+372',NULL,'Estonian'),
    ('SWZ','SZ','Eswatini','+268',NULL,'Swazi'),
    ('ETH','ET','Ethiopia','+251',NULL,'Ethiopian'),
    ('FLK','FK','Falkland Islands [Malvinas]','+500',NULL,'Falkland Islander'),
    ('FRO','FO','Faroe Islands','+298',NULL,'Faroese'),
    ('FJI','FJ','Fiji','+679',NULL,'Fijian'),
    ('FIN','FI','Finland','+358',NULL,'Finnish'),
    ('FRA','FR','France','+33',NULL,'French'),
    ('GUF','GF','French Guiana','+594',NULL,'French Guianan'),
    ('PYF','PF','French Polynesia','+689',NULL,'French Polynesian'),
    ('ATF','TF','French Southern Territories',NULL,NULL,'French Southern Territories'),
    ('GAB','GA','Gabon','+241',NULL,'Gabonese'),
    ('GMB','GM','Gambia','+220',NULL,'Gambian'),
    ('GEO','GE','Georgia','+995',NULL,'Georgian'),
    ('DEU','DE','Germany','+49',NULL,'German'),
    ('GHA','GH','Ghana','+233',NULL,'Ghanaian'),
    ('GIB','GI','Gibraltar','+350',NULL,'Gibraltarian'),
    ('GRC','GR','Greece','+30',NULL,'Greek'),
    ('GRL','GL','Greenland','+299',NULL,'Greenlander'),
    ('GRD','GD','Grenada','+1-473',NULL,'Grenadian'),
    ('GLP','GP','Guadeloupe','+590',NULL,'Guadeloupean'),
    ('GUM','GU','Guam','+1-671',NULL,'Guamanian'),
    ('GTM','GT','Guatemala','+502',NULL,'Guatemalan'),
    ('GGY','GG','Guernsey','+44',NULL,'Channel Islander'),
    ('GIN','GN','Guinea','+224',NULL,'Guinean'),
    ('GNB','GW','Guinea-Bissau','+245',NULL,'Bissau-Guinean'),
    ('GUY','GY','Guyana','+592',NULL,'Guyanese'),
    ('HTI','HT','Haiti','+509',NULL,'Haitian'),
    ('HMD','HM','Heard Island and McDonald Islands',NULL,NULL,'Heard Islander'),
    ('VAT','VA','Holy See','+39',NULL,'Vatican citizen'),
    ('HND','HN','Honduras','+504',NULL,'Honduran'),
    ('HKG','HK','Hong Kong','+852',NULL,'Hong Konger'),
    ('HUN','HU','Hungary','+36',NULL,'Hungarian'),
    ('ISL','IS','Iceland','+354',NULL,'Icelander'),
    ('IND','IN','India','+91',NULL,'Indian'),
    ('IDN','ID','Indonesia','+62',NULL,'Indonesian'),
    ('IRN','IR','Iran (Islamic Republic of)','+98',NULL,'Iranian'),
    ('IRQ','IQ','Iraq','+964',NULL,'Iraqi'),
    ('IRL','IE','Ireland','+353',NULL,'Irish'),
    ('IMN','IM','Isle of Man','+44',NULL,'Manx'),
    ('ISR','IL','Israel','+972',NULL,'Israeli'),
    ('ITA','IT','Italy','+39',NULL,'Italian'),
    ('JAM','JM','Jamaica','+1-876',NULL,'Jamaican'),
    ('JPN','JP','Japan','+81',NULL,'Japanese'),
    ('JEY','JE','Jersey','+44',NULL,'Channel Islander'),
    ('JOR','JO','Jordan','+962',NULL,'Jordanian'),
    ('KAZ','KZ','Kazakhstan','+7',NULL,'Kazakhstani'),
    ('KEN','KE','Kenya','+254',NULL,'Kenyan'),
    ('KIR','KI','Kiribati','+686',NULL,'I-Kiribati'),
    ('PRK','KP','Korea (Democratic People''s Republic of)','+850',NULL,'North Korean'),
    ('KOR','KR','Korea, Republic of','+82',NULL,'South Korean'),
    ('KWT','KW','Kuwait','+965',NULL,'Kuwaiti'),
    ('KGZ','KG','Kyrgyzstan','+996',NULL,'Kyrgyz'),
    ('LAO','LA','Lao People''s Democratic Republic','+856',NULL,'Lao'),
    ('LVA','LV','Latvia','+371',NULL,'Latvian'),
    ('LBN','LB','Lebanon','+961',NULL,'Lebanese'),
    ('LSO','LS','Lesotho','+266',NULL,'Basotho'),
    ('LBR','LR','Liberia','+231',NULL,'Liberian'),
    ('LBY','LY','Libya','+218',NULL,'Libyan'),
    ('LIE','LI','Liechtenstein','+423',NULL,'Liechtensteiner'),
    ('LTU','LT','Lithuania','+370',NULL,'Lithuanian'),
    ('LUX','LU','Luxembourg','+352',NULL,'Luxembourger'),
    ('MAC','MO','Macao','+853',NULL,'Macanese'),
    ('MDG','MG','Madagascar','+261',NULL,'Malagasy'),
    ('MWI','MW','Malawi','+265',NULL,'Malawian'),
    ('MYS','MY','Malaysia','+60',NULL,'Malaysian'),
    ('MDV','MV','Maldives','+960',NULL,'Maldivian'),
    ('MLI','ML','Mali','+223',NULL,'Malian'),
    ('MLT','MT','Malta','+356',NULL,'Maltese'),
    ('MHL','MH','Marshall Islands','+692',NULL,'Marshallese'),
    ('MTQ','MQ','Martinique','+596',NULL,'Martiniquais'),
    ('MRT','MR','Mauritania','+222',NULL,'Mauritanian'),
    ('MUS','MU','Mauritius','+230',NULL,'Mauritian'),
    ('MYT','YT','Mayotte','+262',NULL,'Mahoran'),
    ('MEX','MX','Mexico','+52',NULL,'Mexican'),
    ('FSM','FM','Micronesia (Federated States of)','+691',NULL,'Micronesian'),
    ('MDA','MD','Moldova, Republic of','+373',NULL,'Moldovan'),
    ('MCO','MC','Monaco','+377',NULL,'Monegasque'),
    ('MNG','MN','Mongolia','+976',NULL,'Mongolian'),
    ('MNE','ME','Montenegro','+382',NULL,'Montenegrin'),
    ('MSR','MS','Montserrat','+1-664',NULL,'Montserratian'),
    ('MAR','MA','Morocco','+212',NULL,'Moroccan'),
    ('MOZ','MZ','Mozambique','+258',NULL,'Mozambican'),
    ('MMR','MM','Myanmar','+95',NULL,'Burmese'),
    ('NAM','NA','Namibia','+264',NULL,'Namibian'),
    ('NRU','NR','Nauru','+674',NULL,'Nauruan'),
    ('NPL','NP','Nepal','+977',NULL,'Nepali'),
    ('NLD','NL','Netherlands','+31',NULL,'Dutch'),
    ('NCL','NC','New Caledonia','+687',NULL,'New Caledonian'),
    ('NZL','NZ','New Zealand','+64',NULL,'New Zealander'),
    ('NIC','NI','Nicaragua','+505',NULL,'Nicaraguan'),
    ('NER','NE','Niger','+227',NULL,'Nigerien'),
    ('NGA','NG','Nigeria','+234',NULL,'Nigerian'),
    ('NIU','NU','Niue','+683',NULL,'Niuean'),
    ('NFK','NF','Norfolk Island','+672',NULL,'Norfolk Islander'),
    ('MNP','MP','Northern Mariana Islands','+1-670',NULL,'Northern Marianan'),
    ('NOR','NO','Norway','+47',NULL,'Norwegian'),
    ('OMN','OM','Oman','+968',NULL,'Omani'),
    ('PAK','PK','Pakistan','+92',NULL,'Pakistani'),
    ('PLW','PW','Palau','+680',NULL,'Palauan'),
    ('PSE','PS','Palestine, State of','+970',NULL,'Palestinian'),
    ('PAN','PA','Panama','+507',NULL,'Panamanian'),
    ('PNG','PG','Papua New Guinea','+675',NULL,'Papua New Guinean'),
    ('PRY','PY','Paraguay','+595',NULL,'Paraguayan'),
    ('PER','PE','Peru','+51',NULL,'Peruvian'),
    ('PHL','PH','Philippines','+63',NULL,'Filipino'),
    ('PCN','PN','Pitcairn','+870',NULL,'Pitcairn Islander'),
    ('POL','PL','Poland','+48',NULL,'Polish'),
    ('PRT','PT','Portugal','+351',NULL,'Portuguese'),
    ('PRI','PR','Puerto Rico','+1-787',NULL,'Puerto Rican'),
    ('QAT','QA','Qatar','+974',NULL,'Qatari'),
    ('REU','RE','Réunion','+262',NULL,'Réunionese'),
    ('ROU','RO','Romania','+40',NULL,'Romanian'),
    ('RUS','RU','Russian Federation','+7',NULL,'Russian'),
    ('RWA','RW','Rwanda','+250',NULL,'Rwandan'),
    ('BLM','BL','Saint Barthélemy','+590',NULL,'Saint Barthélemy islander'),
    ('SHN','SH','Saint Helena, Ascension and Tristan da Cunha','+290',NULL,'Saint Helenian'),
    ('KNA','KN','Saint Kitts and Nevis','+1-869',NULL,'Kittitian or Nevisian'),
    ('LCA','LC','Saint Lucia','+1-758',NULL,'Saint Lucian'),
    ('MAF','MF','Saint Martin (French part)','+590',NULL,'Saint-Martinois'),
    ('SPM','PM','Saint Pierre and Miquelon','+508',NULL,'Saint-Pierrais or Miquelonnais'),
    ('VCT','VC','Saint Vincent and the Grenadines','+1-784',NULL,'Saint Vincentian'),
    ('WSM','WS','Samoa','+685',NULL,'Samoan'),
    ('SMR','SM','San Marino','+378',NULL,'Sammarinese'),
    ('STP','ST','Sao Tome and Principe','+239',NULL,'São Toméan'),
    ('SAU','SA','Saudi Arabia','+966',NULL,'Saudi'),
    ('SEN','SN','Senegal','+221',NULL,'Senegalese'),
    ('SRB','RS','Serbia','+381',NULL,'Serbian'),
    ('SYC','SC','Seychelles','+248',NULL,'Seychellois'),
    ('SLE','SL','Sierra Leone','+232',NULL,'Sierra Leonean'),
    ('SGP','SG','Singapore','+65',NULL,'Singaporean'),
    ('SXM','SX','Sint Maarten (Dutch part)','+1-721',NULL,'Sint Maartener'),
    ('SVK','SK','Slovakia','+421',NULL,'Slovak'),
    ('SVN','SI','Slovenia','+386',NULL,'Slovenian'),
    ('SLB','SB','Solomon Islands','+677',NULL,'Solomon Islander'),
    ('SOM','SO','Somalia','+252',NULL,'Somali'),
    ('ZAF','ZA','South Africa','+27',NULL,'South African'),
    ('SGS','GS','South Georgia and the South Sandwich Islands',NULL,NULL,'South Georgia Islander'),
    ('SSD','SS','South Sudan','+211',NULL,'South Sudanese'),
    ('ESP','ES','Spain','+34',NULL,'Spanish'),
    ('LKA','LK','Sri Lanka','+94',NULL,'Sri Lankan'),
    ('SDN','SD','Sudan','+249',NULL,'Sudanese'),
    ('SUR','SR','Suriname','+597',NULL,'Surinamese'),
    ('SJM','SJ','Svalbard and Jan Mayen','+47',NULL,'Svalbard Islander'),
    ('SWE','SE','Sweden','+46',NULL,'Swedish'),
    ('CHE','CH','Switzerland','+41',NULL,'Swiss'),
    ('SYR','SY','Syrian Arab Republic','+963',NULL,'Syrian'),
    ('TWN','TW','Taiwan','+886',NULL,'Taiwanese'),
    ('TJK','TJ','Tajikistan','+992',NULL,'Tajikistani'),
    ('TZA','TZ','Tanzania, United Republic of','+255',NULL,'Tanzanian'),
    ('THA','TH','Thailand','+66',NULL,'Thai'),
    ('TLS','TL','Timor-Leste','+670',NULL,'Timorese'),
    ('TGO','TG','Togo','+228',NULL,'Togolese'),
    ('TKL','TK','Tokelau','+690',NULL,'Tokelauan'),
    ('TON','TO','Tonga','+676',NULL,'Tongan'),
    ('TTO','TT','Trinidad and Tobago','+1-868',NULL,'Trinidadian or Tobagonian'),
    ('TUN','TN','Tunisia','+216',NULL,'Tunisian'),
    ('TUR','TR','Türkiye','+90',NULL,'Turkish'),
    ('TKM','TM','Turkmenistan','+993',NULL,'Turkmen'),
    ('TCA','TC','Turks and Caicos Islands','+1-649',NULL,'Turks and Caicos Islander'),
    ('TUV','TV','Tuvalu','+688',NULL,'Tuvaluan'),
    ('UGA','UG','Uganda','+256',NULL,'Ugandan'),
    ('UKR','UA','Ukraine','+380',NULL,'Ukrainian'),
    ('ARE','AE','United Arab Emirates','+971',NULL,'Emirati'),
    ('GBR','GB','United Kingdom of Great Britain and Northern Ireland','+44',NULL,'British'),
    ('USA','US','United States of America','+1',NULL,'American'),
    ('UMI','UM','United States Minor Outlying Islands',NULL,NULL,'US Islander'),
    ('URY','UY','Uruguay','+598',NULL,'Uruguayan'),
    ('UZB','UZ','Uzbekistan','+998',NULL,'Uzbekistani'),
    ('VUT','VU','Vanuatu','+678',NULL,'Ni-Vanuatu'),
    ('VEN','VE','Venezuela (Bolivarian Republic of)','+58',NULL,'Venezuelan'),
    ('VNM','VN','Viet Nam','+84',NULL,'Vietnamese'),
    ('VGB','VG','Virgin Islands (British)','+1-284',NULL,'British Virgin Islander'),
    ('VIR','VI','Virgin Islands (U.S.)','+1-340',NULL,'U.S. Virgin Islander'),
    ('WLF','WF','Wallis and Futuna','+681',NULL,'Wallisian or Futunan'),
    ('ESH','EH','Western Sahara','+212',NULL,'Sahrawi'),
    ('YEM','YE','Yemen','+967',NULL,'Yemeni'),
    ('ZMB','ZM','Zambia','+260',NULL,'Zambian'),
    ('ZWE','ZW','Zimbabwe','+263',NULL,'Zimbabwean')
) AS v(Alpha1, Alpha2, Name, AreaCode, Flag, Nationality);
