INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(1,'Adv','Advertising and Promotions')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(2,'Agr','Agriculture/Fish/Forestry')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(3,'Ban','Banking/FinancialInstitution')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(4,'Cem','Cement')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(5,'Con','Construction')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(6,'Con','Consultancy')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(7,'Edu','Education')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(8,'Ele','Electricity/Gas/Water')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(9,'Eve','Events Coordinator')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(10,'Ent','Entertainment and Arts')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(11,'Fer','Fertilizers')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(12,'Foo','Food Services')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(13,'Hea','Health and Wellness')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(14,'Hou','Household Employer')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(15,'Inf','Information and Communication')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(16,'Ins','InsuranceAdvertising and Promotions')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(17,'Len','LendingAdvertising and Promotions')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(18,'Liv','Livestock RaisingAdvertising and Promotions')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(19,'Med','Medical ServicesAdvertising and Promotions')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(20,'Mot','Motor Vehicle and PartsAdvertising and Promotions')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(21,'Pri','Printing/PublishingAdvertising and Promotions')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(22,'Pro','Professional PracticeAdvertising and Promotions')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(23,'Pub','Publicly listed companies subject to Regulatory disclosure RequirementsAdvertising and Promotions')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(24,'PUV','PUV OperatorsAdvertising and Promotions')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(25,'Rel','ReligionAdvertising and Promotions')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(26,'Res','Restaurants/Bar/CaféAdvertising and Promotions')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(27,'Sci','Scientific and Technical Activities/Skill ProvidersAdvertising and Promotions')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(28,'Tra','Transportation/Storage and WarehousingAdvertising and Promotions')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(29,'Tru','Trust Entities and Quasi Banks authorized by the BSP to operate as suchAdvertising and Promotions')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(30,'Uti','UtilitiesAdvertising and Promotions')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(31,'Who','Wholesale and RetailAdvertising and Promotions')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(32,'Mar','Market VendorAdvertising and Promotions')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(33,'Stu','StudentAdvertising and Promotions')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(34,'Hou','HousewifeAdvertising and Promotions')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(35,'Aqu','Aquaculture')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(36,'BPO','BPO (Call Center)')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(37,'Che','Chemicals/Petrol/Dye')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(38,'Coa','Coal')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(39,'Cot','Cotton/Textile')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(40,'Eng','Engineering/Electronics')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(41,'Ele','Electricity Generator/Transmitters')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(42,'Ele','Electronics')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(43,'Fin','Financial Services')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(44,'Foo','Food/Beverage Production')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(45,'Foo','Food Processing')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(46,'Hos','Hospitals and Medical Providers')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(47,'Fur','Fur and Substitute of Leather')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(48,'Gas','Gas Industries')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(49,'Hot','Hotels/Resorts/Accommodations')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(50,'Inf','Infrastructure Power')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(51,'Inf','Infrastructure Roads and Parts')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(52,'Inf','Infrastructure Telecom')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(53,'Iro','Iron and Steel')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(54,'Lea','Leather and Leather Products')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(55,'Mac','Machine Parts Manufacturing')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(56,'Man','Manufacturing')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(57,'Med','Media')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(58,'Met','Metal Products')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(59,'Mul','Multinational')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(61,'Pap','Paper and Paper Products Petroleum')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(62,'Pro','Protective Services')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(63,'Rub','Rubber and Rubber Products')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(64,'Soc','Social Services')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(65,'Sug','Sugar')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(66,'Tea','Tea')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(67,'Tel','Telecommunications')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(68,'Tex','Textile')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(69,'Tob','Tobacco')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(70,'Tra','Transportation Operators')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(71,'Tra','Travel and Tourism')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(72,'Veg','Vegetable Oil')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(73,'Web','Web and Social Media')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(74,'Une','Unemployed')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(75,'Air','Airline Industry')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(76,'Auc','Auctioneer')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(77,'Bro','Brokerage')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(78,'Car','Car/Truck/Boat/Plane Dealer')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(79,'Cas','Casinos')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(81,'Com','Computer Software')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(82,'Dru','Drugs and Pharmaceuticals')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(83,'Gov','Government Services')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(84,'Imp','Import/Export Company')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(85,'Jew','Jewels/Gems/Precious Metals Dealer')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(86,'Min','Mining and Quarrying')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(87,'Mon','Money Changer')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(88,'Nuc','Nuclear Fuel')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(89,'Onl','Online Business')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(90,'Onl','Online Gaming/Internet Gambling')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(91,'Paw','Pawnshop/Broker')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(92,'Rea','Real Estate Activities')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(93,'Shi','Ship/Plane/Bus Operator')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(94,'For','Foreign Exchange Dealers/Money Changers')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(95,'NGO','NGOs')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(96,'Rem','Remittance Agents')
INSERT [gen].[IndustryType] ([IndustryTypeId],[Code],[Description])VALUES(97,'She','Shell Companies')
