INSERT INTO gen.Province (ProvinceId, Code, Description) VALUES
(1, 'ILN', 'Ilocos Norte'),
(2, 'ILS', 'Ilocos Sur'),
(3, 'LU', 'La Union'),
(4, 'PAN', 'Pangasinan'),
(5, 'BAT', 'Batanes'),
(6, 'CAG', 'Cagayan'),
(7, 'ISA', 'Isabela'),
(8, 'NV', 'Nueva Vizcaya'),
(9, 'QUI', 'Quirino'),
(10, 'AUR', 'Aurora'),
(11, 'BAT', 'Bataan'),
(12, 'BUL', 'Bulacan'),
(13, 'NE', 'Nueva Ecija'),
(14, 'PAM', 'Pampanga'),
(15, 'TAR', 'Tarlac'),
(16, 'ZAM', 'Zambales'),
(17, 'BAT', 'Batangas'),
(18, 'CAV', 'Cavite'),
(19, 'LAG', 'Laguna'),
(20, 'QZN', 'Quezon'),
(21, 'RZL', 'Rizal'),
(22, 'MDQ', 'Marinduque'),
(23, 'OCM', 'Occidental Mindoro'),
(24, 'ORM', 'Oriental Mindoro'),
(25, 'PAL', 'Palawan'),
(26, 'RBL', 'Romblon'),
(27, 'ALB', 'Albay'),
(28, 'CAMN', 'Camarines Norte'),
(29, 'CAMS', 'Camarines Sur'),
(30, 'CAT', 'Catanduanes'),
(31, 'MAS', 'Masbate'),
(32, 'SOR', 'Sorsogon'),
(33, 'ABR', 'Abra'),
(34, 'APA', 'Apayao'),
(35, 'BEN', 'Benguet'),
(36, 'IFG', 'Ifugao'),
(37, 'KAL', 'Kalinga'),
(38, 'MP', 'Mountain Province'),
(39, 'MM', 'Metro Manila'),
(40, 'AKL', 'Aklan'),
(41, 'ANT', 'Antique'),
(42, 'CPZ', 'Capiz'),
(43, 'GUI', 'Guimaras'),
(44, 'ILO', 'Iloilo'),
(45, 'NOC', 'Negros Occidental'),
(46, 'BHL', 'Bohol'),
(47, 'CBU', 'Cebu'),
(48, 'NOR', 'Negros Oriental'),
(49, 'SIQ', 'Siquijor'),
(50, 'BIL', 'Biliran'),
(51, 'ES', 'Eastern Samar'),
(52, 'LEY', 'Leyte'),
(53, 'NS', 'Northern Samar'),
(54, 'SAM', 'Samar'),
(55, 'SL', 'Southern Leyte'),
(56, 'ZDN', 'Zamboanga del Norte'),
(57, 'ZDS', 'Zamboanga del Sur'),
(58, 'SIB', 'Zamboanga Sibugay'),
(59, 'BKD', 'Bukidnon'),
(60, 'CAM', 'Camiguin'),
(61, 'LDN', 'Lanao del Norte'),
(62, 'MOC', 'Misamis Occidental'),
(63, 'MOR', 'Misamis Oriental'),
(64, 'DDO', 'Davao de Oro'),
(65, 'DDN', 'Davao del Norte'),
(66, 'DDS', 'Davao del Sur'),
(67, 'DOC', 'Davao Occidental'),
(68, 'DOR', 'Davao Oriental'),
(69, 'COT', 'Cotabato'),
(70, 'SAR', 'Sarangani'),
(71, 'SCOT', 'South Cotabato'),
(72, 'SK', 'Sultan Kudarat'),
(73, 'AND', 'Agusan del Norte'),
(74, 'ADS', 'Agusan del Sur'),
(75, 'DIS', 'Dinagat Islands'),
(76, 'SDN', 'Surigao del Norte'),
(77, 'SDS', 'Surigao del Sur'),
(78, 'BAS', 'Basilan'),
(79, 'LDS', 'Lanao del Sur'),
(80, 'MAG', 'Maguindanao'),
(81, 'SUL', 'Sulu'),
(82, 'TAW', 'Tawi-Tawi');
